-- Cargar configuraciones de plugins
require('plugins.colors')
require('plugins.treesitter')
require('plugins.lsp')
require('plugins.mason')
require('plugins.statusline')
require('plugins.rainbow')
require('plugins.telescope')
require('plugins.gitsigns')
require('plugins.comment')
require('plugins.autopairs')
require('plugins.bufferline')
require('plugins.toggleterm')
require('plugins.alpha')